# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
parameters:
  maya-devkit-url:
    type: string
    default: "https://autodesk-adn-transfer.s3-us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2019/Autodesk_Maya_2019_3_Update_DEVKIT_Windows.zip"
  maya-devkit-path:
    type: string
    default: C:\\devkit
  cmake-path:
    type: string
    default: "C:\\Program Files\\CMake"
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the windows orb
  win: circleci/windows@2.2.0
# Orchestrate or schedule a set of jobs
jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    environment:
      DEVKIT_LOCATION: C:\\devkit\\devkitBase
    steps:
        # Commands are run in a Windows virtual machine environment
        - checkout
        - restore_cache:
            keys: 
              - maya-devkit
        - run:
            name: Install Maya DevKit
            command: |
              if (-not (Test-Path -LiteralPath << pipeline.parameters.maya-devkit-path >>)) {
                $ProgressPreference = "SilentlyContinue"
                Invoke-WebRequest << pipeline.parameters.maya-devkit-url >> -OutFile devkit.zip
                Expand-Archive -LiteralPath devkit.zip -DestinationPath << pipeline.parameters.maya-devkit-path >>
                ls << pipeline.parameters.maya-devkit-path >>
                "Successfully installed Maya Dev Kit."
              }
              else {
                "Maya Dev Kit was loaded from cache."
              }
           
        - save_cache:
            key: maya-devkit
            paths:
              - << pipeline.parameters.maya-devkit-path >>
              
        - restore_cache:
            keys: 
              - cmake-install
              
        - run: 
            name: Install CMake
            command: |
              if (-not (Test-Path -LiteralPath << pipeline.parameters.cmake-path >>)) {
                choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
                "Successfully installed CMake."
              }
              else {
                "CMake was loaded from cache."
              }
              ls "C:\Program Files\CMake"
              ls "C:\Program Files\CMake\bin"
             
        - save_cache:
            key: cmake-install
            paths:
              - C:\Program Files\CMake

        - run:
            name: Create build directory
            shell: cmd.exe
            command: |
                cd C:\Users\circleci
                mkdir maya-plugin
        - run:
            name: Configure project
            command: |
                $vsPath = &(Join-Path ${env:ProgramFiles(x86)} "\Microsoft Visual Studio\Installer\vswhere.exe") -property installationpath
                Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
                Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments “-arch=amd64″

                if (-not (Get-Command cmake -ErrorAction SilentlyContinue)) {
                  New-Alias -Name cmake -Value "<< pipeline.parameters.cmake-path >>\bin\cmake.exe"
                }
                $env:DEVKIT_LOCATION
                cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - NMake Makefiles" -S C:\Users\circleci\project -B C:\Users\circleci\maya-plugin
        - run:
            name: Build project
            command: |
                $vsPath = &(Join-Path ${env:ProgramFiles(x86)} "\Microsoft Visual Studio\Installer\vswhere.exe") -property installationpath
                Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
                Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments “-arch=amd64″

                if (-not (Get-Command cmake -ErrorAction SilentlyContinue)) {
                  New-Alias -Name cmake -Value "<< pipeline.parameters.cmake-path >>\bin\cmake.exe"
                }
                cmake --build C:\Users\circleci\maya-plugin --target all
